stages:
  - build
  - deploy

variables:
  # from https://storage.googleapis.com/kubernetes-release/release/stable.txt
  K8S_STABLE_VERSION_URL: https://storage.googleapis.com/kubernetes-release/release/v1.10.4/bin/linux/amd64/kubectl

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    #- export DOCKER_VERSION=$(echo "$CI_BUILD_REF" | cut -c 1-6)    
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/frozen-frond-h-thon/api .
    - docker push registry.gitlab.com/frozen-frond-h-thon/api
    - docker build -t registry.gitlab.com/moose0030/frozen-frond-h-thon/api .
    - docker push registry.gitlab.com/frozen-frond-h-thon/api

deploy_dev:
  stage: deploy
  image: alpine
  environment:
    name: Dev
  script:
    - echo $KUBECONFIG
    - echo $KUBECONTEXT 
    - apk add --no-cache curl
    - curl -LO $K8S_STABLE_VERSION_URL
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - mkdir ~/.kube
    - cp $KUBECONFIG ~/.kube/config
    - cat ~/.kube/config
    - kubectl config use-context gitlab-deploy
    - kubectl cluster-info dump
    #- CONTAINER_LOWERCASE=$(echo $CI_PROJECT_PATH | tr '[:upper:]' '[:lower:]')
    - IMAGE="registry.gitlab.com/frozen-frond-h-thon/api"
    - sed 's#_ENV_#'$LB_ENV'#g; s#_IMAGE_#"'$IMAGE'"#g' kubernetes.tpl.yml > kubernetes.yml;
    - kubectl delete secrets/regcred-api 
    - kubectl create secret docker-registry regcred-api --docker-server="registry.gitlab.com/frozen-frond-h-thon/api" --docker-username=$KUBERNETES_EMAIL --docker-password=$KUBERNETES_PASSWORD --kubeconfig=$KUBECONFIG
    - kubectl apply -f kubernetes.yml
    # - kubectl apply -f deploy 
    # If no error, connection to the cluster from the pipeline script is OK
    # TODO: write a deploy script