kind: Service
apiVersion: v1
metadata:
  name: service-api
spec:
  #type: NodePort
  selector:
    app: pod-api
  ports:
  - name: web
    port: 80
    targetPort: 3004
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-api
    spec:
      containers:
      - name: container-api
        image: 
        ports:
        - containerPort: 3004
      imagePullSecrets:
      - name: regcred-api